"""
Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
import environ
import re
from django.template import base
import dj_database_url


env = environ.Env()
environ.Env.read_env()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# '.railway.app', 
ALLOWED_HOSTS = ['.linguo.ai']

# 'https://*.railway.app', 
CSRF_TRUSTED_ORIGINS = ['https://*.linguo.ai']


INSTALLED_APPS = [
    'daphne',
    'channels',
    'tz_detect',
    "home",
    "members",
    'landing_pages',

    "imagekit",
    "lazy_srcset",

    'blog',
    'wagtail.contrib.forms',
    'wagtail.contrib.redirects',
    'wagtail.embeds',
    'wagtail.sites',
    'wagtail.users',
    'wagtail.snippets',
    'wagtail.documents',
    'wagtail.images',
    'wagtail.search',
    'wagtail.admin',
    'wagtail',
    'modelcluster',
    'taggit',

    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sitemaps"
]

MIDDLEWARE = [
    'wagtail.contrib.redirects.middleware.RedirectMiddleware',
    'django.middleware.security.SecurityMiddleware',
     "whitenoise.middleware.WhiteNoiseMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'tz_detect.middleware.TimezoneMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'linguoai.urls'

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]





DATABASES = {
    'default': dj_database_url.config(
        conn_max_age=600,
        conn_health_checks=True,
    ),
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL ='members.User'

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATIC_URL = 'static/'

# STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

INTERNAL_IPS = [
    "0.0.0.0"
]

LOGIN_REDIRECT_URL = '/dash/'


MEDIA_URL = 'media/'

MEDIA_ROOT = os.environ["RAILWAY_VOLUME_MOUNT_PATH"]
# MEDIA_ROOT = 'https://linguo.ai/app/media/'

# img_dir = os.path.join(MEDIA_ROOT, 'images')
# if not os.path.exists(img_dir):
#   os.makedirs(img_dir)



# For collecting the enduser's country
GEOIP_PATH = "linguoai/geoip"

# EMAIL_HOST = "localhost"
# EMAIL_PORT = 1025

EMAIL_BACKEND = 'django_ses.SESBackend' 

# Access just for local testing
AWS_ACCESS_KEY_ID = env('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = env('AWS_SECRET_ACCESS_KEY')


ASSETS_ROOT = STATIC_URL

# Allows you to put the tags on multiple lines - used in FAQs
base.tag_re = re.compile(base.tag_re.pattern, re.DOTALL)


ASGI_APPLICATION = "linguoai.asgi.application"
# WSGI_APPLICATION = 'linguoai.wsgi.application'


# WEBPACK_LOADER = {
#   'DEFAULT': {
#     'CACHE': not DEBUG,
#     'STATS_FILE': os.path.join(BASE_DIR, 'webpack-stats.json'),
#     'POLL_INTERVAL': 0.1,
#     'IGNORE': [r'.+\.hot-update.js', r'.+\.map'],
#   }
# }


WAGTAIL_SITE_NAME = 'LinguoAI'
WAGTAILADMIN_BASE_URL = 'cms/'
WAGTAILIMAGES_IMAGE_MODEL = 'blog.CustomImage'



OPENAI_API_KEY = env('OPENAI_API_KEY')

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [(env('REDIS_URL'))],
        },
    },
}


DATE_FORMAT = 'D, jS M y, g:i a'
SHORT_DATE_FORMAT = 'jS M y, P'

# Stop localization
USE_L10N = False



LAZY_SRCSET_ENABLED = True

# The default threshold to use when not specified in the config.
LAZY_SRCSET_THRESHOLD = 69

# The default generator to use when not specified in the config.
LAZY_SRCSET_GENERATOR_ID = "lazy_srcset:srcset_image"

LAZY_SRCSET = {
    "default": {
        # breakpoints is the only setting you must define
        # "breakpoints": [1920, 1580, 1280, 1024, 640],
        "breakpoints": [1920, 1100, 767],

        # If max_width is not provided the source image width is used.
        # It's a good idea to set this.
        "max_width": 2560,
        # If quality is not provided PIL will choose a default
        "quality": 91,
        # If format is not provided the source image format is used
        "format": "WEBP",
        # The difference in width (px) required to generate a new image
        # This prevents images being created which are too similar in size
        "threshold": LAZY_SRCSET_THRESHOLD,
        # If generator_id is not provided LAZY_SRCSET_GENERATOR_ID is used
        "generator_id": LAZY_SRCSET_GENERATOR_ID,
    }
}





# CACHES = {
#     "default": {
#         "BACKEND": "django.core.cache.backends.redis.RedisCache",
#         "LOCATION": env('REDIS_URL'),
#         "OPTIONS": {
#             "db": "10",
#             "parser_class": "redis.connection.PythonParser",
#             "pool_class": "redis.BlockingConnectionPool",
#         },
#     }
# }

CSRF_COOKIE_SECURE = True

SESSION_COOKIE_SECURE = True

SECURE_HSTS_SECONDS = 3600

SECURE_HSTS_INCLUDE_SUBDOMAINS = True

SECURE_HSTS_PRELOAD = True

BASE_URL = 'https://linguo.ai'

# Django deployment warnings edit
# SECURE_SSL_REDIRECT = True
# SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTOCOL', 'https')


