# Generated by Django 4.2.3 on 2023-08-09 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_blogtagindexpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='profile',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
