# Generated by Django 4.2.3 on 2023-08-09 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_author_profile_alter_author_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='profile',
            field=models.TextField(),
        ),
    ]
