# Generated by Django 4.2.6 on 2023-11-06 10:16

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields
import members.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(error_messages={'unique': 'That email address has already been registered. Please use another one.'}, max_length=254, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='email address')),
                ('first_name', models.CharField(max_length=150, verbose_name='Name')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('year', models.PositiveIntegerField(default=2003, validators=[django.core.validators.MinValueValidator(1920, 'Whooaa, looks like the year you entered was a little early. Have a go at entering a year after 1920.'), members.models.max_year])),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('reports', models.PositiveIntegerField(default=0)),
                ('total_submissions', models.PositiveIntegerField(default=0)),
                ('percent_reported', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('reports_blocked', models.BooleanField(default=False)),
                ('currency', models.CharField(choices=[('USD', '$ United States Dollar'), ('CNY', '¥ Chinese RMB')], default='USD', max_length=3)),
                ('total_spent', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('discount_code_used', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Affiliate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_joined', models.DateField()),
                ('website', models.CharField(blank=True, max_length=150)),
                ('social_media_app', models.CharField(blank=True, choices=[('FB', 'Facebook'), ('X', 'X'), ('TT', 'Tik Tok'), ('IN', 'Instagram'), ('DY', 'Douyin')], max_length=2)),
                ('social_media_handle', models.CharField(blank=True, max_length=50, unique=True)),
                ('currency', models.CharField(choices=[('USD', '$ United States Dollar'), ('CNY', '¥ Chinese RMB')], default='USD', max_length=3)),
                ('total_sales', models.PositiveIntegerField(default=0)),
                ('total_new_users', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CorrectedSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_used', models.CharField(max_length=128)),
                ('prompt_tokens', models.PositiveIntegerField()),
                ('completion_tokens', models.PositiveIntegerField()),
                ('total_tokens', models.PositiveIntegerField()),
                ('total_words', models.PositiveIntegerField()),
                ('currency', models.CharField(max_length=3)),
                ('cost', models.DecimalField(decimal_places=6, max_digits=10)),
                ('price_per_100_words', models.DecimalField(decimal_places=3, max_digits=6)),
                ('charged', models.DecimalField(decimal_places=2, max_digits=7)),
                ('usd_charge', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('usd_exchange_rate', models.DecimalField(decimal_places=6, max_digits=8)),
                ('profit', models.DecimalField(decimal_places=3, max_digits=8)),
                ('margin', models.DecimalField(decimal_places=3, max_digits=8)),
                ('processing_time', models.DecimalField(decimal_places=3, max_digits=6)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('user_reported', models.BooleanField(default=False)),
                ('user_deleted', models.BooleanField(default=False)),
                ('new_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('comments', models.TextField()),
                ('submission', models.TextField(validators=[members.models.max_word_count_general_validator])),
                ('result', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Corrected Submissions',
            },
        ),
        migrations.CreateModel(
            name='DiscountCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_name', models.CharField(max_length=50, unique=True)),
                ('code_title', models.CharField(blank=True, max_length=150)),
                ('discount_code', models.CharField(max_length=30)),
                ('currency', models.CharField(choices=[('USD', '$ United States Dollar'), ('CNY', '¥ Chinese RMB')], default='USD', max_length=3)),
                ('bonus_amount', models.PositiveSmallIntegerField(default=0)),
                ('bonus_percent', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('for_purchases', models.BooleanField(default=False)),
                ('first_purchase', models.BooleanField(default=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('expiry_date', models.DateField()),
                ('times_used', models.PositiveIntegerField(default=0)),
                ('total_cost', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'Discount Codes',
            },
        ),
        migrations.CreateModel(
            name='IeltsWritingTask2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_used', models.CharField(max_length=128)),
                ('prompt_tokens', models.PositiveIntegerField()),
                ('completion_tokens', models.PositiveIntegerField()),
                ('total_tokens', models.PositiveIntegerField()),
                ('total_words', models.PositiveIntegerField()),
                ('currency', models.CharField(max_length=3)),
                ('cost', models.DecimalField(decimal_places=6, max_digits=10)),
                ('price_per_100_words', models.DecimalField(decimal_places=3, max_digits=6)),
                ('charged', models.DecimalField(decimal_places=2, max_digits=7)),
                ('usd_charge', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('usd_exchange_rate', models.DecimalField(decimal_places=6, max_digits=8)),
                ('profit', models.DecimalField(decimal_places=3, max_digits=8)),
                ('margin', models.DecimalField(decimal_places=3, max_digits=8)),
                ('processing_time', models.DecimalField(decimal_places=3, max_digits=6)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('user_reported', models.BooleanField(default=False)),
                ('user_deleted', models.BooleanField(default=False)),
                ('new_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('comments', models.TextField()),
                ('explanation_language', models.CharField(choices=[('EN', 'English'), ('CN', 'Chinese 中文'), ('ES', 'Spanish Español'), ('PT', 'Portuguese Português'), ('FR', 'French Français'), ('DE', 'German Deutsch'), ('JP', 'Japanese 日本語'), ('KO', 'Korean 한국어'), ('TH', 'Thai แบบไทย'), ('AR', 'Arabic عربي'), ('RU', 'Russian русский'), ('ID', 'Indonesian bahasa Indonesia'), ('FA', 'Farsi فارسی'), ('VI', 'Vietnamese Tiếng Việt'), ('BN', 'Bengali বাংলা'), ('HI', 'Hindi हिंदी')], default='EN', max_length=2)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('score_res', models.TextField()),
                ('band', models.CharField(max_length=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'IELTS Writing Task 2',
            },
        ),
        migrations.CreateModel(
            name='ImprovedSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_used', models.CharField(max_length=128)),
                ('prompt_tokens', models.PositiveIntegerField()),
                ('completion_tokens', models.PositiveIntegerField()),
                ('total_tokens', models.PositiveIntegerField()),
                ('total_words', models.PositiveIntegerField()),
                ('currency', models.CharField(max_length=3)),
                ('cost', models.DecimalField(decimal_places=6, max_digits=10)),
                ('price_per_100_words', models.DecimalField(decimal_places=3, max_digits=6)),
                ('charged', models.DecimalField(decimal_places=2, max_digits=7)),
                ('usd_charge', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('usd_exchange_rate', models.DecimalField(decimal_places=6, max_digits=8)),
                ('profit', models.DecimalField(decimal_places=3, max_digits=8)),
                ('margin', models.DecimalField(decimal_places=3, max_digits=8)),
                ('processing_time', models.DecimalField(decimal_places=3, max_digits=6)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('user_reported', models.BooleanField(default=False)),
                ('user_deleted', models.BooleanField(default=False)),
                ('new_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('comments', models.TextField()),
                ('submission', models.TextField(validators=[members.models.max_word_count_general_validator])),
                ('improved_sub', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Improved Submissions',
            },
        ),
        migrations.CreateModel(
            name='UserReportedResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField()),
                ('decision', models.CharField(choices=[('Waiting', 'Awaiting Approval'), ('Accepted', 'Accepted'), ('Declined', 'Declined')], default='Waiting', max_length=10)),
                ('refunded', models.BooleanField(default=False)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('comments', models.TextField()),
                ('corrected', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='members.correctedsubmission')),
                ('ielts_writing_task_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='members.ieltswritingtask2')),
                ('improved', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='members.improvedsubmission')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Reported Results',
            },
        ),
        migrations.CreateModel(
            name='PurchaseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('payment_method', models.CharField(default='Stripe', max_length=20)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Total Purchases',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='affiliate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='members.affiliate'),
        ),
        migrations.AddField(
            model_name='user',
            name='discount_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='members.discountcodes'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
