# Generated by Django 4.2.3 on 2023-08-11 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ieltswritingtask2',
            name='explanation_language',
            field=models.CharField(choices=[('EN', 'English'), ('CN', 'Chinese - 中文'), ('ES', 'Spanish - Español'), ('PT', 'Portuguese - Português'), ('FR', 'French - Français'), ('DE', 'German - Deutsch'), ('JP', 'Japanese - 日本語'), ('KO', 'Korean - 한국어'), ('TH', 'Thai - แบบไทย'), ('HI', 'Hindi - हिंदी'), ('AR', 'Arabic - عربي'), ('BN', 'Bengali - বাংলা'), ('RU', 'Russian - русский'), ('ID', 'Indonesian - bahasa Indonesia'), ('FA', 'Farsi - فارسی'), ('VI', 'Vietnamese - Tiếng Việt')], default='EN', max_length=2),
        ),
    ]
