# Generated by Django 4.2.6 on 2023-11-14 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correctedsubmission',
            name='price_per_100_words',
            field=models.DecimalField(decimal_places=5, max_digits=7),
        ),
        migrations.AlterField(
            model_name='ieltswritingtask2',
            name='price_per_100_words',
            field=models.DecimalField(decimal_places=5, max_digits=7),
        ),
        migrations.AlterField(
            model_name='improvedsubmission',
            name='price_per_100_words',
            field=models.DecimalField(decimal_places=5, max_digits=7),
        ),
    ]
