# Generated by Django 4.2.1 on 2023-06-04 14:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correctedsubmission',
            name='submission',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='ieltsscore',
            name='answer',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(200)]),
        ),
        migrations.AlterField(
            model_name='ieltsscore',
            name='question',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(200)]),
        ),
        migrations.AlterField(
            model_name='improvedsubmission',
            name='submission',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(200)]),
        ),
    ]
