# Generated by Django 4.2.1 on 2023-06-29 02:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_correctedsubmission_submission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correctedsubmission',
            name='submission',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(5000)]),
        ),
        migrations.AlterField(
            model_name='ieltsscore',
            name='answer',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(2500)]),
        ),
        migrations.AlterField(
            model_name='ieltsscore',
            name='question',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(100)]),
        ),
        migrations.AlterField(
            model_name='improvedsubmission',
            name='submission',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(5000)]),
        ),
    ]
