# Generated by Django 4.2.3 on 2023-08-12 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_ieltswritingtask2_explanation_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reports_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ieltswritingtask2',
            name='explanation_language',
            field=models.CharField(choices=[('EN', 'English'), ('CN', 'Chinese 中文'), ('ES', 'Spanish Español'), ('PT', 'Portuguese Português'), ('FR', 'French Français'), ('DE', 'German Deutsch'), ('JP', 'Japanese 日本語'), ('KO', 'Korean 한국어'), ('TH', 'Thai แบบไทย'), ('AR', 'Arabic عربي'), ('RU', 'Russian русский'), ('ID', 'Indonesian bahasa Indonesia'), ('FA', 'Farsi فارسی'), ('VI', 'Vietnamese Tiếng Việt'), ('BN', 'Bengali বাংলা'), ('HI', 'Hindi हिंदी')], default='EN', max_length=2),
        ),
    ]
