# Generated by Django 4.2.6 on 2023-11-18 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_ieltswritingtask2_explanation_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='correctedsubmission',
            old_name='price_per_100_words',
            new_name='price_per_word',
        ),
        migrations.RenameField(
            model_name='ieltswritingtask2',
            old_name='price_per_100_words',
            new_name='price_per_word',
        ),
        migrations.RenameField(
            model_name='improvedsubmission',
            old_name='price_per_100_words',
            new_name='price_per_word',
        ),
    ]
