# Generated by Django 4.2.3 on 2023-07-29 04:21

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_correctedsubmission_submission_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IeltsWritingTask2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_used', models.CharField(max_length=128)),
                ('prompt_tokens', models.PositiveIntegerField()),
                ('completion_tokens', models.PositiveIntegerField()),
                ('total_tokens', models.PositiveIntegerField()),
                ('processing_time', models.FloatField()),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('credits_used', models.PositiveIntegerField()),
                ('question', models.TextField(validators=[django.core.validators.MaxLengthValidator(100)])),
                ('answer', models.TextField(validators=[django.core.validators.MaxLengthValidator(3000)])),
                ('score_res', models.TextField()),
                ('band', models.CharField(max_length=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserReportedResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField()),
                ('accepted', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='correctedsubmission',
            name='submission',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(25000)]),
        ),
        migrations.AlterField(
            model_name='improvedsubmission',
            name='submission',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(25000)]),
        ),
        migrations.DeleteModel(
            name='IeltsScore',
        ),
        migrations.AddField(
            model_name='userreportedresults',
            name='corrected',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.correctedsubmission'),
        ),
        migrations.AddField(
            model_name='userreportedresults',
            name='ielts_writing_task_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.ieltswritingtask2'),
        ),
        migrations.AddField(
            model_name='userreportedresults',
            name='improved',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.improvedsubmission'),
        ),
        migrations.AddField(
            model_name='userreportedresults',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
