# Generated by Django 4.2.3 on 2023-08-25 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_rename_corrections_correctedsubmission_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correctedsubmission',
            name='usd_exchange_rate',
            field=models.DecimalField(decimal_places=6, max_digits=8),
        ),
        migrations.AlterField(
            model_name='ieltswritingtask2',
            name='usd_exchange_rate',
            field=models.DecimalField(decimal_places=6, max_digits=8),
        ),
        migrations.AlterField(
            model_name='improvedsubmission',
            name='usd_exchange_rate',
            field=models.DecimalField(decimal_places=6, max_digits=8),
        ),
    ]
