# Generated by Django 4.2.3 on 2023-07-29 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_ieltswritingtask2_userreportedresults_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userreportedresults',
            options={'verbose_name_plural': 'IELTS Writing Task 2 '},
        ),
    ]
