# Generated by Django 4.2.3 on 2023-07-29 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_alter_userreportedresults_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ieltswritingtask2',
            options={'verbose_name_plural': 'IELTS Writing Task 2 '},
        ),
        migrations.AlterModelOptions(
            name='userreportedresults',
            options={'verbose_name_plural': 'User Reported Results'},
        ),
        migrations.AlterField(
            model_name='userreportedresults',
            name='corrected',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='members.correctedsubmission'),
        ),
        migrations.AlterField(
            model_name='userreportedresults',
            name='ielts_writing_task_2',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='members.ieltswritingtask2'),
        ),
        migrations.AlterField(
            model_name='userreportedresults',
            name='improved',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='members.improvedsubmission'),
        ),
    ]
