# Generated by Django 4.2.3 on 2023-09-16 09:23

from django.db import migrations, models
import members.models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_alter_correctedsubmission_usd_exchange_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correctedsubmission',
            name='submission',
            field=models.TextField(validators=[members.models.max_word_count_general_validator]),
        ),
        migrations.AlterField(
            model_name='improvedsubmission',
            name='submission',
            field=models.TextField(validators=[members.models.max_word_count_general_validator]),
        ),
    ]
