# Generated by Django 4.2.3 on 2023-07-29 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_alter_ieltswritingtask2_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreportedresults',
            name='corrected',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='members.correctedsubmission'),
        ),
        migrations.AlterField(
            model_name='userreportedresults',
            name='ielts_writing_task_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='members.ieltswritingtask2'),
        ),
        migrations.AlterField(
            model_name='userreportedresults',
            name='improved',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='members.improvedsubmission'),
        ),
    ]
