# Generated by Django 4.2.3 on 2023-09-16 09:51

from django.db import migrations, models
import members.models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_alter_correctedsubmission_submission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ieltswritingtask2',
            name='answer',
            field=models.TextField(validators=[members.models.min_word_count_ielts_a_validator, members.models.max_word_count_ielts_a_validator]),
        ),
        migrations.AlterField(
            model_name='ieltswritingtask2',
            name='question',
            field=models.TextField(validators=[members.models.min_word_count_ielts_a_validator, members.models.max_word_count_ielts_a_validator]),
        ),
    ]
