# Generated by Django 4.2.3 on 2023-07-29 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_alter_userreportedresults_corrected_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reports',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='total_submissions',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
