# Generated by Django 4.2.3 on 2023-07-29 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_user_reports_user_total_submissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='correctedsubmission',
            name='user_reported',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ieltswritingtask2',
            name='user_reported',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='improvedsubmission',
            name='user_reported',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
