# Generated by Django 4.2.3 on 2023-07-29 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_correctedsubmission_user_reported_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ieltswritingtask2',
            options={'verbose_name_plural': 'IELTS Writing Task 2'},
        ),
        migrations.AddField(
            model_name='correctedsubmission',
            name='charged',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='correctedsubmission',
            name='cost',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='correctedsubmission',
            name='profit',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ieltswritingtask2',
            name='charged',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ieltswritingtask2',
            name='cost',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ieltswritingtask2',
            name='profit',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='improvedsubmission',
            name='charged',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='improvedsubmission',
            name='cost',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='improvedsubmission',
            name='profit',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
