# Generated by Django 4.2.3 on 2023-07-29 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_alter_ieltswritingtask2_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='correctedsubmission',
            name='margin',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ieltswritingtask2',
            name='margin',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='improvedsubmission',
            name='margin',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='correctedsubmission',
            name='user_reported',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ieltswritingtask2',
            name='user_reported',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='improvedsubmission',
            name='user_reported',
            field=models.BooleanField(default=False),
        ),
    ]
