# Generated by Django 4.2.3 on 2023-07-29 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_correctedsubmission_margin_ieltswritingtask2_margin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='correctedsubmission',
            name='total_words',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ieltswritingtask2',
            name='total_words',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='improvedsubmission',
            name='total_words',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
