# Generated by Django 4.2.3 on 2023-07-29 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_correctedsubmission_total_words_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='correctedsubmission',
            name='price_per_100_words',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ieltswritingtask2',
            name='price_per_100_words',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='improvedsubmission',
            name='price_per_100_words',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
