# Generated by Django 4.2.3 on 2023-07-29 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0013_correctedsubmission_price_per_100_words_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='correctedsubmission',
            name='credits_used',
        ),
        migrations.RemoveField(
            model_name='ieltswritingtask2',
            name='credits_used',
        ),
        migrations.RemoveField(
            model_name='improvedsubmission',
            name='credits_used',
        ),
    ]
