# Generated by Django 4.2.3 on 2023-07-29 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0014_remove_correctedsubmission_credits_used_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='credits',
        ),
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='balance_currency',
            field=models.CharField(default='USD', max_length=3),
        ),
    ]
