# Generated by Django 4.2.3 on 2023-07-29 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0015_remove_user_credits_user_balance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasehistory',
            name='credits_bought',
        ),
        migrations.AddField(
            model_name='purchasehistory',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
    ]
