# Generated by Django 4.2.3 on 2023-07-29 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0016_remove_purchasehistory_credits_bought_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='correctedsubmission',
            name='user_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ieltswritingtask2',
            name='user_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='improvedsubmission',
            name='user_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
