# Generated by Django 4.2.3 on 2023-07-29 14:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0017_correctedsubmission_user_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='correctedsubmission',
            name='comments',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ieltswritingtask2',
            name='comments',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='improvedsubmission',
            name='comments',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ieltswritingtask2',
            name='question',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(500)]),
        ),
        migrations.AlterField(
            model_name='userreportedresults',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
