# Generated by Django 4.2.3 on 2023-07-29 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0018_correctedsubmission_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='correctedsubmission',
            name='refunded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ieltswritingtask2',
            name='refunded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='improvedsubmission',
            name='refunded',
            field=models.BooleanField(default=False),
        ),
    ]
