# Generated by Django 4.2.3 on 2023-07-31 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0020_alter_correctedsubmission_charged_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correctedsubmission',
            name='cost',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ieltswritingtask2',
            name='cost',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
        migrations.AlterField(
            model_name='improvedsubmission',
            name='cost',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
    ]
