# Generated by Django 4.2.3 on 2023-07-31 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0021_alter_correctedsubmission_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='correctedsubmission',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='ieltswritingtask2',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='improvedsubmission',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
    ]
