# Generated by Django 4.2.3 on 2023-07-31 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0022_correctedsubmission_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasehistory',
            name='payment_method',
            field=models.CharField(default='Stripe', max_length=20),
        ),
    ]
