# Generated by Django 4.2.3 on 2023-08-05 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0023_purchasehistory_payment_method'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='balance_currency',
            new_name='currency',
        ),
    ]
