# Generated by Django 4.2.3 on 2023-08-05 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0024_rename_balance_currency_user_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('CNY', 'Chinese RMB')], default='USD', max_length=3),
        ),
    ]
