# Generated by Django 4.2.3 on 2023-08-05 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0026_alter_user_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='correctedsubmission',
            name='usd_exchange_rate',
            field=models.DecimalField(decimal_places=2, default=0.14, max_digits=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ieltswritingtask2',
            name='usd_exchange_rate',
            field=models.DecimalField(decimal_places=2, default=0.14, max_digits=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='improvedsubmission',
            name='usd_exchange_rate',
            field=models.DecimalField(decimal_places=2, default=0.14, max_digits=7),
            preserve_default=False,
        ),
    ]
