# Generated by Django 4.2.3 on 2023-08-05 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0027_correctedsubmission_usd_exchange_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correctedsubmission',
            name='currency',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='ieltswritingtask2',
            name='currency',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='improvedsubmission',
            name='currency',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='purchasehistory',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
