# Generated by Django 4.2.3 on 2023-08-05 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0028_alter_correctedsubmission_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='correctedsubmission',
            name='usd_charge',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ieltswritingtask2',
            name='usd_charge',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='improvedsubmission',
            name='usd_charge',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7),
            preserve_default=False,
        ),
    ]
