# Generated by Django 4.2.3 on 2023-08-05 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0029_correctedsubmission_usd_charge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correctedsubmission',
            name='usd_charge',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='ieltswritingtask2',
            name='usd_charge',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='improvedsubmission',
            name='usd_charge',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
