# Generated by Django 4.2.3 on 2023-08-05 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0030_alter_correctedsubmission_usd_charge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='percent_reported',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
            preserve_default=False,
        ),
    ]
