# Generated by Django 4.2.3 on 2023-08-05 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0031_user_percent_reported'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='percent_reported',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
    ]
