# Generated by Django 4.2.3 on 2023-08-06 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0032_alter_user_percent_reported'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='correctedsubmission',
            name='refunded',
        ),
        migrations.RemoveField(
            model_name='ieltswritingtask2',
            name='refunded',
        ),
        migrations.RemoveField(
            model_name='improvedsubmission',
            name='refunded',
        ),
    ]
