# Generated by Django 4.2.3 on 2023-08-06 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0033_remove_correctedsubmission_refunded_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userreportedresults',
            name='accepted',
        ),
        migrations.AddField(
            model_name='userreportedresults',
            name='decision',
            field=models.CharField(choices=[('Waiting', 'Awaiting Approval'), ('Accepted', 'Accepted'), ('Declined', 'Declined')], default='Waiting', max_length=10),
        ),
    ]
