# Generated by Django 4.2.3 on 2023-08-06 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0034_remove_userreportedresults_accepted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreportedresults',
            name='comments',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
