# Generated by Django 4.2.3 on 2023-08-06 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0035_userreportedresults_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreportedresults',
            name='refunded',
            field=models.BooleanField(default=False),
        ),
    ]
