# Generated by Django 4.2.3 on 2023-08-06 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0036_userreportedresults_refunded'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreportedresults',
            name='refund_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
            preserve_default=False,
        ),
    ]
