# Generated by Django 4.2.3 on 2023-08-07 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0038_alter_userreportedresults_refund_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='correctedsubmission',
            name='new_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ieltswritingtask2',
            name='new_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='improvedsubmission',
            name='new_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
